# Generated by Django 3.2 on 2021-04-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('vacant_beds', models.IntegerField()),
            ],
        ),
    ]
